version: "3.9"
services:
  db:
    image: postgres:14.3
    container_name: transfermoney-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
